controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

examples_external_services:
    resource:
        path: ../examples/01-external-services/
        namespace: App\Example\ExternalServices
    type: attribute
    prefix: external-services

examples_massive_hydration:
    resource:
        path: ../examples/02-massive-hydration/
        namespace: App\Example\MassiveHydration
    type: attribute
    prefix: massive-hydration

examples_query_stream:
    resource:
        path: ../examples/03-query-stream/
        namespace: App\Example\QueryStream
    type: attribute
    prefix: query-stream